import { COLORS } from "../../theme/style-constants";

export const CorridorMarkerIcon = () => (
  <div style={{ width: "100px", height: "150px" }}>
    <svg width="150" height="150" viewBox="0 0 200 200">
      {/* Solid filled center circle */}
      <circle cx="100" cy="100" r="6" fill={COLORS.textColorDark} />

      {/* Animated rings */}
      <circle
        cx="100"
        cy="100"
        r="10"
        fill="none"
        stroke={COLORS.textColorDark}
        strokeWidth="2"
      >
        <animate
          attributeName="r"
          from="10"
          to="90"
          dur="2s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="opacity"
          from="1"
          to="0"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        cx="100"
        cy="100"
        r="10"
        fill="none"
        stroke={COLORS.textColorDark}
        strokeWidth="2"
      >
        <animate
          attributeName="r"
          from="10"
          to="90"
          begin="0.5s"
          dur="2s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="opacity"
          from="1"
          to="0"
          begin="0.5s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        cx="100"
        cy="100"
        r="10"
        fill="none"
        stroke={COLORS.textColorDark}
        strokeWidth="2"
      >
        <animate
          attributeName="r"
          from="10"
          to="90"
          begin="1s"
          dur="2s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="opacity"
          from="1"
          to="0"
          begin="1s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        cx="100"
        cy="100"
        r="10"
        fill="none"
        stroke={COLORS.textColorDark}
        strokeWidth="2"
      >
        <animate
          attributeName="r"
          from="10"
          to="90"
          begin="1.5s"
          dur="2s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="opacity"
          from="1"
          to="0"
          begin="1.5s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
    </svg>
  </div>
);
